# Generated by Django 4.2.8 on 2023-12-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_company', models.CharField(max_length=100)),
                ('car_company_name', models.CharField(max_length=100)),
            ],
        ),
    ]
