# Generated by Django 4.2.8 on 2023-12-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
