# Generated by Django 4.2.8 on 2023-12-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_practice', '0002_car_fuel_car_price_car_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='system',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
